repository: Domi04151309/domi04151309.github.io

highlighter: none

gems:
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-titles-from-headings

markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter_opts:
      disable : true

languages: [ "en" ]

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "Arduino"
    values:
      layout: "default_green"
