url: https://domi04151309.github.io

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "Android"
    values:
      layout: "project"
  - scope:
      path: "Arduino"
    values:
      layout: "default_green"
