url: https://domi04151309.github.io

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "Android"
    values:
      layout: "project"
  - scope:
      path: "Linux"
    values:
      layout: "project"
  - scope:
      path: "Web"
    values:
      layout: "project"
  - scope:
      path: "Windows"
    values:
      layout: "project"
