gems:
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-titles-from-headings

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "Arduino"
    values:
      layout: "default_green"
