name: Continuous Integration (JavaScript)

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.ts'
      - '**.json'
  pull_request:
    branches:
      - main

concurrency:
  group: ci-js-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install
      - name: Run
        run: bun run eslint
  tsc:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: |
          bun install
          bun add -d github:anvil-solutions/build
      - name: Run
        run: bun run tsc
